replicaCount: 1
applicationName: aksworkshop

image:
  repository: basket
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

env:
  values:
    - name: PATH_BASE
      value: /basket-api

keyVault:
  secrets: basketconstr
  secretsTypes: secret
